M48
; DRILL file {KiCad 7.0.7-7.0.7~ubuntu20.04.1} date Tue Aug 29 15:56:37 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-08-29T15:56:37+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7-7.0.7~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X1.4961Y-6.2205
X1.4961Y-7.0079
T0
M30
