; bed.g
; called to perform automatic bed compensation via G32
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Mon Oct 23 2023 15:47:39 GMT+0100 (British Summer Time)
M561 ; clear any bed transform
G29  ; probe the bed and enable compensation


