; stop.g
; called when M0 (Stop) is run (e.g. when a print from SD card is cancelled)
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Mon Oct 23 2023 15:47:40 GMT+0100 (British Summer Time)

