; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool v3.3.16 on Mon Oct 23 2023 15:47:40 GMT+0100 (British Summer Time)
; Wait for set temperatures to be reached
M116 P0

